### ISSUE TITLE
no jniLLVM library found

### ISSUE THREAD

**Issue by Nacharuvsko** [superblaubeere27/masxinlingvonta#7]
I'm getting the `java.lang.UnsatisfiedLinkError: no jniLLVM in java.library.path` issue while trying to run masxinlingvonta.
I built masxinlingvonta by myself.
Tried on LLVM versions: `clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04` and `clang+llvm-13.0.0-aarch64-linux-gnu`

`java -jar masxinlingvonta-cli-0.1.0-SNAPSHOT.jar -i input.jar -o obfuscated.jar -compileFor linux -llvmDir "/home/winston/LLVM/bin"
Loading input...
Compiling...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniLLVM in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1328)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at org.bytedeco.llvm.global.LLVM.<clinit>(LLVM.java:14)
	at net.superblaubeere27.masxinlingvaj.compiler.MLVCompiler.createModule(MLVCompiler.java:29)
	at net.superblaubeere27.masxinlingvaj.compiler.MLVCompiler.<init>(MLVCompiler.java:25)
	at net.superblaubeere27.masxinlingvaj.MLV.preprocessAndCompile(MLV.java:40)
	at net.superblaubeere27.masxinlingvonta.CLIMain.main(CLIMain.java:100)
Caused by: java.lang.UnsatisfiedLinkError: no Remarks in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1239)
	... 6 more
`

Any solutions? Thanks.

**Comment by superblaubeere27** [comment]
Which command did you use to compile the repo? `clang+llvm-13.0.0-aarch64-linux-gnu` is probably not going to work since currently only x86 architectures are supported. `clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04` should work fine though

**Comment by Nacharuvsko** [comment]
I used `mvn -Djavacpp.platform=linux-x86_64 clean package` to build it. Even when using `clang+llvm-13.0.0-x86_64-linux-gnu-ubuntu-20.04` im getting the same error.

**Comment by superblaubeere27** [comment]
`jniLLVM not found` means that `masxinlingvonta` wasn't packaged properly. This seems to be a problem with java-cpp, I can't reproduce it though.

**Comment by Just1ceP4rtn3r** [comment]
Hello, any solutions to this question? And I use `masxinlingvonta` with llvm-9+clang-9 in ubuntu-20.04.

**Comment by superblaubeere27** [comment]
> Hello, any solutions to this question? And I use `masxinlingvonta` with llvm-9+clang-9 in ubuntu-20.04.

JavaCpp should download a bundled version of LLVM. Are you sure that you build the project properly?
